/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juego;

import java.awt.Color;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Cintia Ortiz
 */
public class TresEnRaya extends javax.swing.JFrame {

    int jugador1 = 1;
    int jugador2 = 2;

    int turno = 0;

    boolean fin_jeugo = false;

//    boolean turno = true;
    /**
     * Creates new form TresEnRaya
     */
    public TresEnRaya() {
        initComponents();

        setSize(500, 500);

        casillas();

        lbl();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        lbl6 = new javax.swing.JLabel();
        lbl7 = new javax.swing.JLabel();
        lbl8 = new javax.swing.JLabel();
        lbl9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tres en raya");
        getContentPane().setLayout(new java.awt.GridLayout(3, 3, 5, 4));
        getContentPane().add(lbl1);
        getContentPane().add(lbl2);
        getContentPane().add(lbl3);
        getContentPane().add(lbl4);
        getContentPane().add(lbl5);
        getContentPane().add(lbl6);
        getContentPane().add(lbl7);
        getContentPane().add(lbl8);
        getContentPane().add(lbl9);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TresEnRaya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TresEnRaya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TresEnRaya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TresEnRaya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TresEnRaya().setVisible(true);
            }
        });
    }

    Image img = new ImageIcon("juego/o.jpg").getImage();
    ImageIcon img2 = new ImageIcon(img.getScaledInstance(159, 150, Image.SCALE_SMOOTH));
    Image img1 = new ImageIcon("juego/x.png").getImage();
    ImageIcon img3 = new ImageIcon(img1.getScaledInstance(159, 150, Image.SCALE_SMOOTH));

    public void lbl() {

        lbl1.addMouseListener(new MouseAdapter() {

            public void mouseClicked(MouseEvent e) {

                if (turno == 0) {
                    lbl1.setIcon(img2);
                    turno++;
                } else {
                    lbl1.setIcon(img3);
                    turno = 0;

                }
                comprobarGanador();
            }

        });

        lbl2.addMouseListener(new MouseAdapter() {

            public void mouseClicked(MouseEvent e) {
                if (turno == 0) {

                    lbl2.setIcon(img2);
                    turno++;
                } else {

                    lbl2.setIcon(img3);
                    turno = 0;
                    ;
                }
                comprobarGanador();
            }
        });

        lbl3.addMouseListener(new MouseAdapter() {

            public void mouseClicked(MouseEvent e) {

                if (turno == 0) {

                    lbl3.setIcon(img2);
                    turno++;
                } else {

                    lbl3.setIcon(img3);
                    turno = 0;
                }
                comprobarGanador();
            }
        });

        lbl4.addMouseListener(new MouseAdapter() {

            public void mouseClicked(MouseEvent e) {

                if (turno == 0) {

                    lbl4.setIcon(img2);
                    turno++;
                } else {

                    lbl4.setIcon(img3);
                    turno = 0;
                }
                comprobarGanador();
            }
        });

        lbl5.addMouseListener(new MouseAdapter() {

            public void mouseClicked(MouseEvent e) {

                if (turno == 0) {

                    lbl5.setIcon(img2);
                    turno++;
                } else {

                    lbl5.setIcon(img3);
                    turno = 0;
                }
                comprobarGanador();
            }
        });

        lbl6.addMouseListener(new MouseAdapter() {

            public void mouseClicked(MouseEvent e) {

                if (turno == 0) {

                    lbl6.setIcon(img2);
                    turno++;
                } else {

                    lbl6.setIcon(img3);
                    turno = 0;
                }
                comprobarGanador();
            }
        });

        lbl7.addMouseListener(new MouseAdapter() {

            public void mouseClicked(MouseEvent e) {

                if (turno == 0) {

                    lbl7.setIcon(img2);
                    turno++;
                } else {

                    lbl7.setIcon(img3);
                    turno = 0;
                }
                comprobarGanador();
            }
        });

        lbl8.addMouseListener(new MouseAdapter() {

            public void mouseClicked(MouseEvent e) {

                if (turno == 0) {

                    lbl8.setIcon(img2);
                    turno++;
                } else {

                    lbl8.setIcon(img3);
                    turno = 0;
                }
                comprobarGanador();
            }
        });

        lbl9.addMouseListener(new MouseAdapter() {

            public void mouseClicked(MouseEvent e) {

                if (turno == 0) {

                    lbl9.setIcon(img2);
                    turno++;
                } else {

                    lbl9.setIcon(img3);
                    turno = 0;
                }
                comprobarGanador();
            }
        });

    }

    public void comprobarGanador() {
        
        //Línea horizontal arriba ------
        if (lbl1.getIcon() != null && lbl2.getIcon() != null && lbl3.getIcon() != null && lbl1.getIcon() == lbl2.getIcon() && lbl2.getIcon() == lbl3.getIcon()) {

            JOptionPane.showMessageDialog(null, "¡Has ganado!", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            resetea();
            return;
        }
        // //Línea vertical izquierda
        if (lbl1.getIcon() != null && lbl4.getIcon() != null && lbl7.getIcon() != null && lbl1.getIcon() == lbl4.getIcon() && lbl4.getIcon() == lbl7.getIcon()) {

            JOptionPane.showMessageDialog(null, "¡Has ganado!", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            resetea();
            return;
        }
        ////Diagonal izquierda
        if (lbl1.getIcon() != null && lbl5.getIcon() != null && lbl9.getIcon() != null && lbl1.getIcon() == lbl5.getIcon() && lbl5.getIcon() == lbl9.getIcon()) {

            JOptionPane.showMessageDialog(null, "¡Has ganado!", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            resetea();
            return;
        }
        //horizontal del medio      
        if (lbl4.getIcon() != null && lbl5.getIcon() != null && lbl6.getIcon() != null && lbl4.getIcon() == lbl5.getIcon() && lbl4.getIcon() == lbl6.getIcon()) {

            JOptionPane.showMessageDialog(null, "¡Has ganado!", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            resetea();
            return;
        }
        // Línea horizontal inferior       
        if (lbl7.getIcon() != null && lbl8.getIcon() != null && lbl9.getIcon() != null && lbl7.getIcon() == lbl8.getIcon() && lbl8.getIcon() == lbl9.getIcon()) {

            JOptionPane.showMessageDialog(null, "¡Has ganado!", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            resetea();
            return;
        }

        //Línea vertical del medio
        if (lbl2.getIcon() != null && lbl5.getIcon() != null && lbl8.getIcon() != null && lbl2.getIcon() == lbl5.getIcon() && lbl5.getIcon() == lbl8.getIcon()) {

            JOptionPane.showMessageDialog(null, "¡Has ganado!", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            resetea();
            return;
        }

        //Línea vertical derecho
        if (lbl3.getIcon() != null && lbl6.getIcon() != null && lbl9.getIcon() != null && lbl3.getIcon() == lbl6.getIcon() && lbl6.getIcon() == lbl9.getIcon()) {

            JOptionPane.showMessageDialog(null, "¡Has ganado!", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            resetea();
            return;
        }
        //Línea diagonal derecho
        if (lbl3.getIcon() != null && lbl5.getIcon() != null && lbl7.getIcon() != null && lbl3.getIcon() == lbl5.getIcon() && lbl5.getIcon() == lbl7.getIcon()) {

            JOptionPane.showMessageDialog(null, "¡Has ganado!", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            resetea();
            return;
        }

    }
    
    public void resetea(){
        
     lbl1.setIcon(null);
     lbl2.setIcon(null);
     lbl3.setIcon(null);
     lbl4.setIcon(null);
     lbl5.setIcon(null);
     lbl6.setIcon(null);
     lbl7.setIcon(null);
     lbl8.setIcon(null);
     lbl9.setIcon(null);
    
        
    }

    public void casillas() {
        JLabel[] casillas = new JLabel[]{lbl1, lbl2, lbl3, lbl4, lbl5, lbl6, lbl7, lbl8, lbl9};

        for (int i = 0; i < casillas.length; i++) {

            casillas[i].setBorder(BorderFactory.createLineBorder(Color.BLACK));

        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl6;
    private javax.swing.JLabel lbl7;
    private javax.swing.JLabel lbl8;
    private javax.swing.JLabel lbl9;
    // End of variables declaration//GEN-END:variables
}
